services:
  frontend:
    build: shoppify-mern/frontend
    ports:
      - "5173:5173"
    networks:
      - mern
  backend:
    build: shoppify-mern/backend
    ports:
      - "4000:4000"
    networks:
      - mern
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo_data:/data/db

networks:
    mern:
      driver: bridge

volumes:
    mongo_data:
      driver: local   
    